runConnectionPool :: MonadControlIO m => Action m a -> ConnectionPool -> m a
runConnectionPool = runMongoDBConn (ConfirmWrites [u"j" =: True])

withConnectionPool :: (MonadControlIO m, Applicative m) => AppConfig -> (ConnectionPool -> m b) -> m b
withConnectionPool conf f = do
    (database,host) <- liftIO $ loadMongoConnParams (appEnv conf)
    withMongoDBPool (u database) host (connectionPoolSize conf) f

