
{-# LANGUAGE CPP #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE ViewPatterns #-}

module Yesod.Routes.TH.Internal where

import Prelude hiding (exp)
import Data.List (foldl')
import Data.Maybe (mapMaybe)
import Language.Haskell.TH.Syntax
import Web.PathPieces (fromPathPiece)
import Yesod.Routes.TH.Types

conPCompat :: Name -> [Pat] -> Pat
conPCompat n pats = ConP n
#if MIN_VERSION_template_haskell(2,18,0)
                         []
#endif
                         pats

instanceD :: Cxt -> Type -> [Dec] -> Dec
instanceD = InstanceD Nothing

mkTupE :: [Exp] -> Exp
mkTupE =
    TupE
#if MIN_VERSION_template_haskell(2,16,0)
        . fmap Just
#endif

-- | The number of type parameters a type constructor declares (0 for a type
-- that isn't a data\/newtype\/type-synonym, or that we can't reify).
typeArity :: Name -> Q Int
typeArity typeName = do
    info <- reify typeName
    pure $ case info of
        TyConI (DataD _ _ vs _ _ _) -> length vs
        TyConI (NewtypeD _ _ vs _ _ _) -> length vs
        TyConI (TySynD _ vs _) -> length vs
        _ -> 0

-- | Look up a type by 'Name' and return it fully applied with fresh
-- type variables. This is needed because nested route datatypes may
-- have type parameters (e.g., @NestedR subsite@), and TH functions
-- like 'isInstance' require fully-applied types.
fullyApplyType :: Name -> Q Type
fullyApplyType typeName = do
    arity <- typeArity typeName
    vars <- mapM (\i -> VarT <$> newName ("a" ++ show i)) [1..arity]
    pure $ foldl' AppT (ConT typeName) vars

-- | The fully-applied route 'Type' for a (resolved) route datatype 'Name',
-- as used for an instance head or an 'isInstance' probe. With explicit
-- 'TyArgs' (a parameterized site) the supplied type arguments are applied to
-- the constructor; otherwise the datatype is reified and saturated with fresh
-- type variables (needed for e.g. @mkYesodSubDispatch@, which doesn't know the
-- parent's type args).
appliedRouteType :: Name -> TyArgs -> Q Type
appliedRouteType tyname tyargs =
    case tyargs of
        SomeTyArgs{} -> pure $ applyTyArgs (ConT tyname) tyargs
        NoTyArgs     -> fullyApplyType tyname

-- | 'appliedRouteType' starting from the route datatype's name as a 'String':
-- resolve it with 'lookupTypeName' and apply the type arguments, falling back
-- to the bare (unresolved) constructor — still applied to any explicit
-- 'TyArgs' — when the name isn't in scope (e.g. it is defined in the same
-- splice group). The fallback is why this can't be a plain @'lookupTypeName' >>=
-- 'appliedRouteType'@.
appliedRouteTypeNamed :: String -> TyArgs -> Q Type
appliedRouteTypeNamed routeName tyargs = do
    mname <- lookupTypeName routeName
    case mname of
        Just typeName -> appliedRouteType typeName tyargs
        Nothing       -> pure $ applyTyArgs (ConT (mkName routeName)) tyargs

-- | Validate that a parameterized subsite's nested route datatype carries
-- exactly as many type parameters as the subsite has type arguments.
--
-- 'mkYesodSubDispatchInstance' applies the subsite's type arguments to each
-- nested route datatype (e.g. @NestedR subsite@) and uses the result directly
-- as the head of a @YesodSubDispatchNested@ instance, which expects a fully
-- applied (kind 'Type') route. So the arities must match exactly:
--
--   * Too few parameters on the nested datatype (e.g. it was generated by
--     plain 'mkYesodSubData', kind 'Type') over-applies it.
--   * Too many leaves it partially applied (kind @Type -> ...@).
--
-- Either way the result is a kind error reported deep inside generated code.
-- This turns it into an actionable, attributable message (suitable for
-- 'fail').
--
-- Pure so it can be unit-tested directly.
checkNestedSubArity
    :: String  -- ^ subsite type name
    -> String  -- ^ nested route datatype name
    -> Int     -- ^ number of the subsite's type arguments
    -> Int     -- ^ declared arity of the nested route datatype
    -> Either String ()
checkNestedSubArity subName nestedName subArgs nestedArity
    | subArgs == nestedArity = Right ()
    | otherwise = Left $ concat
        [ "mkYesodSubDispatchInstance: the nested route datatype `", nestedName
        , "` has ", show nestedArity, " type parameter(s), but the subsite `"
        , subName, "` has ", show subArgs
        , ". The subroute datatypes must carry exactly the subsite's type "
        , "parameter(s) — generate the subsite's routes with "
        , "`mkYesodSubDataOpts (setParameterizedSubroute True defaultOpts) ...` "
        , "so a parameterized subsite gets parameterized subroutes."
        ]

-- | Turn a single route piece into a match pattern, returning the freshly
-- bound 'Name' for dynamic pieces (and 'Nothing' for static ones). Abstracted
-- over the fresh-'Name' supply @m@: the 'Q' code generators pass 'newName',
-- while the pure, deterministic inline-parse path passes a 'State' 'Int'
-- counter. This is the single source of truth for the
-- @ViewP fromPathPiece (Just x)@ dynamic encoding shared by the parse and
-- dispatch clause builders.
handlePieceM :: Applicative m => (String -> m Name) -> Piece a -> m (Pat, Maybe Name)
handlePieceM _ (Static str) = pure (LitP $ StringL str, Nothing)
handlePieceM fresh (Dynamic _) = mk <$> fresh "dyn"
  where
    mk x = (ViewP (VarE 'fromPathPiece) (conPCompat 'Just [VarP x]), Just x)

-- | The list form of 'handlePieceM' projecting the dynamic binders as 'Name's,
-- for callers that consume the bound variables directly (e.g. nested-dispatch
-- handler arguments).
handlePiecesNames :: Applicative m => (String -> m Name) -> [Piece a] -> m ([Pat], [Name])
handlePiecesNames fresh =
    fmap (\pps -> (map fst pps, mapMaybe snd pps)) . traverse (handlePieceM fresh)

-- | The list form of 'handlePieceM' projecting the dynamic binders as 'VarE'
-- expressions, for callers that rebuild a route by applying its constructor to
-- the captured pieces.
handlePiecesM :: Applicative m => (String -> m Name) -> [Piece a] -> m ([Pat], [Exp])
handlePiecesM fresh =
    fmap (\(pats, names) -> (pats, map VarE names)) . handlePiecesNames fresh

-- | Build a path match pattern: a list pattern of the given piece patterns
-- ending in a final tail pattern (e.g. @[]@, a @rest@ binder, or 'WildP').
mkPathPat :: Pat -> [Pat] -> Pat
mkPathPat = foldr (\x y -> conPCompat '(:) [x, y])

-- | Generate a single-argument lambda expression with a fresh name.
-- Takes a base name hint, generates a unique 'Name', and passes it
-- to a callback that produces the lambda body. Returns the complete
-- 'LamE' expression.
--
-- For multi-argument lambdas, nest calls — @\\x y -> body@ is
-- equivalent to @\\x -> \\y -> body@.
mkLambda :: String -> (Name -> Q Exp) -> Q Exp
mkLambda hint mkBody = do
    n <- newName hint
    bdy <- mkBody n
    pure $ LamE [VarP n] bdy

-- | Given a target 'String', find the 'ResourceParent' in the
-- @['ResourceTree' a]@ corresponding to that target and return it.
-- Also return the @['Piece' a]@ captures that precede it.
findNestedRoute :: String -> [ResourceTree a] -> Maybe ([Piece a], [ResourceTree a])
findNestedRoute _ [] = Nothing
findNestedRoute target (res : ress) =
    case res of
        ResourceLeaf _ ->
            findNestedRoute target ress
        ResourceParent name _overlap _attrs pieces children -> do
            if name == target
                then Just (pieces, children)
                else
                    let mresult = findNestedRoute target children
                    in
                        case mresult of
                            Nothing -> do
                                findNestedRoute target ress
                            Just (typs, childRoute) -> do
                                Just (pieces <> typs, childRoute)
