{-# LANGUAGE CPP #-}
#if PRODUCTION
import Controller (with~sitearg~)
import Network.Wai.Handler.Warp (run)

main :: IO ()
main = with~sitearg~ $ run 3000
#else
import Controller (with~sitearg~)
import System.IO (hPutStrLn, stderr)
import Network.Wai.Middleware.Debug (debug)
import Network.Wai.Handler.Warp (run)
import Settings (appPort)

main :: IO ()
main = do
    hPutStrLn stderr $ "Application launched, listening on port " ++ show appPort
    with~sitearg~ $ run appPort . debug
#endif

