{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE ViewPatterns #-}

-- | The split-out nested-dispatch instance for @FirstFooR@, generated with the
-- DEFAULT route options — i.e. @fallthrough = False@. The @FooIndexR@\/@FooNeatR@
-- handlers live ONLY here, so the top module ("FallthroughMatrixRuntime") can
-- compile only by delegating to the @YesodDispatchNested FirstFooR@ instance
-- generated by this splice (it cannot inline handlers it can't see).
--
-- Because this module's flag is @False@, the pre-R10 codegen bakes a 404 into
-- FirstFooR's own terminal fallback; that is what silently defeats the top
-- module's @fallthrough = True@ intent.
module YesodCoreTest.FallthroughMatrix.FirstFoo where

import Yesod.Core
import YesodCoreTest.FallthroughMatrix.Resources

mkYesodOpts (setFocusOnNestedRoute "FirstFooR" defaultOpts) "FMApp" fmResources

getFooIndexR :: HandlerFor FMApp String
getFooIndexR = pure "FooIndexR"

getFooNeatR :: HandlerFor FMApp String
getFooNeatR = pure "FooNeatR"
