<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>$title$</title>
    <style>
      body {
        background-color: #ffc;
      }

      #wrapper {
        width: 600px;
        margin: 2em auto;
        background-color: #fefefe;
        border: 1px solid black;
        padding: 1em;
        font-family: sans-serif;
      }
    </style>
  </head>
  <body>
    <div id="wrapper">
      $content$
    </div>
  </body>
</html>
