Yesod uses Persistent for its (you guessed it) persistence layer.
This tool will build in either SQLite, PostgreSQL, or MongoDB support for you.
We recommend starting with SQLite: it has no dependencies.

We have another option: a tiny project with minimal dependencies. In particular: no database and no authentication.

So, what'll it be? s for sqlite, p for postgresql, m for MongoDB, t for tiny: 
