Yesod uses Persistent for its (you guessed it) persistence layer.
This tool will build in either SQLite or PostgreSQL or MongoDB support for you.
We recommend starting with SQLite: it has no dependencies.

We have another option: a tiny project with minimal dependencies.
Mostly this means no database and no authentication.

    s     = sqlite
    p     = postgresql
    mongo = mongodb
    t     = tiny
    mysql = MySQL (experimental)

So, what'll it be? 
